# Generated by Django 6.0.3 on 2026-03-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Рабочее расписание', 'verbose_name_plural': 'Рабочее расписание'},
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='break_start',
        ),
    ]
