# Generated by Django 6.0.3 on 2026-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoff',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Выходной/Нерабочее время', 'verbose_name_plural': 'Выходные и нерабочее время'},
        ),
        migrations.AddField(
            model_name='dayoff',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторяется каждый год'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('full_day', 'Полный день'), ('hours', 'Нерабочие часы'), ('range', 'Диапазон дней')], default='full_day', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.CharField(choices=[('holiday', 'Праздник'), ('vacation', 'Отпуск'), ('sick', 'Больничный'), ('event', 'Мероприятие'), ('technical', 'Технические работы'), ('other', 'Другое')], default='other', max_length=200, verbose_name='Причина'),
        ),
    ]
