name: Deploy to Server

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            # Добавляем исключение для Git от имени django
            su - django -c "git config --global --add safe.directory /home/django/Tilda-Calendar"
            
            cd /home/django/Tilda-Calendar
            
            # Стягиваем изменения
            su - django -c "cd /home/django/Tilda-Calendar && git pull origin release"
            
            # Выполняем команды с полным путем к venv
            su - django -c "cd /home/django/Tilda-Calendar && /home/django/Tilda-Calendar/venv/bin/pip install -r requirements.txt"
            su - django -c "cd /home/django/Tilda-Calendar && /home/django/Tilda-Calendar/venv/bin/python manage.py migrate"
            su - django -c "cd /home/django/Tilda-Calendar && /home/django/Tilda-Calendar/venv/bin/python manage.py collectstatic --noinput"
            
            # Перезапускаем Gunicorn
            systemctl restart gunicorn
            
            echo "✅ Деплой завершен!"